name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: fake private key
      run: touch api/storage/oauth-private.key
    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies (PHP vendors)
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --working-dir=api
    - name: Dockerize
      run: docker build -t ${{ github.repository }}:latest -f api/.docker/Dockerfile api
#        docker build -t ${{ github.repository }}:latest -f api/.docker/Dockerfile api
#        docker tag ${{ github.repository }}:latest docker.pkg.github.com/${{ github.repository }}/wcpredictor2018:latest
    - name: Log in to registry
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u markcameron --password-stdin docker.io
#      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin docker.pkg.github.com
    - name: Push the latest Docker image
      if: success()
      run: docker push ${{ github.repository }}:latest
#      run: docker push docker.pkg.github.com/${{ github.repository }}/wcpredictor2018:latest


#                       docker.pkg.github.com/markcameron/wcpredictor2018/IMAGE_NAME:VERSION

  build:
    name: Build PWA
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install packages
      run: npm install
    - name: Compile VueJS PWA
      run: npm run build
