name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: fake private key
      run: touch api/storage/oauth-private.key
    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies (PHP vendors)
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --working-dir=api

  - uses: mr-smithers-excellent/docker-build-push@v2
    with:
      image: ${{ github.repository }}
      tag: latest
      registry: docker.pkg.github.com
      dockerfile: api/.docker/Dockerfile
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

#                       docker.pkg.github.com/markcameron/wcpredictor2018/IMAGE_NAME:VERSION
